<?php 
// This file is automatically generated at:2022-11-16 16:07:54
declare (strict_types = 1);
return array (
  0 => 'think\\captcha\\CaptchaService',
  1 => 'think\\app\\Service',
  2 => 'think\\trace\\Service',
);